# Generated by Django 2.2 on 2019-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.DurationField()),
                ('DeadLine', models.DateField()),
                ('StartTime', models.DateField()),
                ('InProgress', models.BooleanField()),
            ],
        ),
    ]
