# Generated by Django 2.2.1 on 2019-07-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('Sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='ProjectID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_requests_created', to='project.Scrum'),
        ),
    ]
