# Generated by Django 2.2 on 2019-07-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0002_sprint_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='ProjectID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_requests_created', to='project.Project'),
        ),
    ]
