# Generated by Django 2.2 on 2019-06-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('priority', models.IntegerField(unique=True)),
                ('defenition_done', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=150)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
