# Generated by Django 2.2 on 2019-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
