# Generated by Django 2.2 on 2019-06-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='defenition_done',
            new_name='definition_done',
        ),
    ]
