# Generated by Django 2.2.1 on 2019-06-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backlog', '0002_auto_20190610_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='priority',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
