# Generated by Django 2.2 on 2019-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backlog', '0003_auto_20190613_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
