# Generated by Django 2.2 on 2019-06-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Backlog', '0002_auto_20190601_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('TaskState', models.IntegerField()),
                ('BackLogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backlog.Backlog')),
            ],
        ),
    ]
