# Generated by Django 2.2 on 2019-06-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Backlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('TaskState', models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('TO_DO', 'to do'), ('DONE', 'done')], max_length=12)),
                ('BackLogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backlog.Backlog')),
            ],
        ),
    ]
