# Generated by Django 2.2 on 2019-07-07 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0002_task_picker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pair_picker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_picker', to=settings.AUTH_USER_MODEL),
        ),
    ]
