# Generated by Django 2.2 on 2019-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='UserID',
            new_name='picker',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Task Title', max_length=100),
            preserve_default=False,
        ),
    ]
