# Generated by Django 2.2 on 2019-07-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20190709_0912'),
        ('Task', '0002_task_picker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ProjectID',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
            preserve_default=False,
        ),
    ]
