# Generated by Django 2.2.1 on 2019-06-13 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20190612_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
