# Generated by Django 2.2.1 on 2019-07-04 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreationDate', models.DateField(auto_now_add=True)),
                ('StartDate', models.DateField()),
                ('EndTime', models.DateField()),
                ('Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater_assigned', to=settings.AUTH_USER_MODEL)),
                ('ProjectManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_assigned', to=settings.AUTH_USER_MODEL)),
                ('ScrumMaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_master_assigned', to=settings.AUTH_USER_MODEL)),
                ('TeamMembers', models.ManyToManyField(related_name='team_members_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
