# Generated by Django 2.2.1 on 2019-07-04 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190704_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='TeamMembers',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_members_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
