# Generated by Django 2.2.1 on 2019-07-04 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190704_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='ProjectManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrum',
            name='ScrumMaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_master_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
