# Generated by Django 2.2.1 on 2019-07-05 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_auto_20190704_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUserInvitationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('sent', models.DateTimeField(null=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_of_user', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
