# Generated by Django 2.2.1 on 2019-07-05 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_projectuserinvitationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserinvitationmodel',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
