# Generated by Django 2.2.1 on 2019-07-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190705_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserinvitationmodel',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Scrum'),
        ),
    ]
