# Generated by Django 2.2.1 on 2019-07-05 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190705_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserinvitationmodel',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_of_user', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
