# Generated by Django 2.2.1 on 2019-07-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190705_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserinvitationmodel',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
