# Generated by Django 2.2 on 2019-07-07 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0003_auto_20190707_1401'),
        ('Backlog', '0003_auto_20190707_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_auto_20190705_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='EndDate',
            field=models.DateField(default='2018-01-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Methodology',
            field=models.CharField(choices=[('Scrum', 'scrum'), ('Waterfall', 'waterfall'), ('XP', 'xp')], default='Scrum', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Type',
            field=models.CharField(choices=[('B2B', 'business to business'), ('C2C', 'customer to customer'), ('B2C', 'business to customer')], default='B2B', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectuserinvitationmodel',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.DeleteModel(
            name='Scrum',
        ),
    ]
