# Generated by Django 2.2 on 2019-07-07 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20190707_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
