# Generated by Django 2.2 on 2019-07-09 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0015_auto_20190707_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuserinvitationmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='projectuserinvitationmodel',
            name='UserID',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='id_of_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
