# Generated by Django 2.2 on 2019-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20190709_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserinvitationmodel',
            name='key',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
